name: build

on: [push, pull_request]

jobs:

  linux:
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-18.04]
        compiler: [clang++-8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
    - name: Compile tests
      working-directory: sql
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        cmake -DBUILD_TESTING=ON ..
        make -j12
    - name: Collect outputs
      run: |
        mkdir _output
        dir ..
        dir ../Bin
        cp ..\Bin\* _output
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: _output
    - name: Run tests
      working-directory: sql
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 20 -C Debug -j12

  windows:
    timeout-minutes: 20

    strategy:
      matrix:
        os: [windows-2019]
        include:
          - os: windows-2019
            generator: Visual Studio 16 2019

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
    - name: Compile tests
      working-directory: sql
      run: |
        cmake .. -A Win32 -DBUILD_TESTING=ON -DBUILD_CLIENT=0 -DCMAKE_CXX_FLAGS=/W1 -G"${{ matrix.generator }}"
        cmake --build . -j 12
    - name: Collect outputs
      run: |
        mkdir _output
        dir ..
        dir ../Bin
        copy ..\Bin\* _output
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: _output
    - name: Run tests
      working-directory: sql
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 20 -C Debug -j12
